### ISSUE TITLE
Module jakarta.activation not found, required by org.jvnet.staxex

### ISSUE THREAD

**Issue by cbos** [eclipse-ee4j/jaxb-stax-ex#22]
For Java11 analysis we are testing the with latest TomEE8, there we found a problems with stax-ex 1.8.1. We run the tools jdeps from the JDK.

`
Exception in thread "main" java.lang.module.FindException: Module jakarta.activation not found, required by org.jvnet.staxex
       at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
       at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
       at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
       at java.base/java.lang.module.Configuration.resolve(Configuration.java:411)
       at java.base/java.lang.module.Configuration.resolve(Configuration.java:245)
       at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration.<init>(JdepsConfiguration.java:117)
       at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:563)
       at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:589)
       at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:543)
       at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:519)
       at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
`

b9396664146e447b9d92d67072c39647714e30e8 This commit has changed all kind of references from javax.activitation to jakarta.activitation. 

The Java module (not the Maven module) where activation is defined is javax.activation.
Stax-ex defines the module-info.java where the dependencies are defined.
That now also contains jakarta.activation as dependency, but that does not exit.

Do to this all jdeps checks we run with stax-ex on the classpath fail, so we don't have results for other dependencies as well.

#21 Might be related to this as well.

**Comment by cbos** [comment]
I created a pull request #23 for this ticket

**Comment by lukasj** [comment]
jakarta.activation java module exists, see the project's pom, which has dependency on:

```
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>1.2.1</version>
        </dependency>
 ```
where `jakarta.activation` module is defined. Should you need the same module with the implementation, use:

```
        <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>jakarta.activation</artifactId>
            <version>1.2.1</version>
        </dependency>
 ```

**Comment by cbos** [comment]
@lukasj Thanks for your reply.
I guess the confusion comes because developers are looking for the replacement of javax.activation which is only one jar. Only that jar is replaced.
jakarta.activation does not have a dependency on jakarta.activation-api and jakarta.activation only advertises javax.activitation. 
stax-ex has a maven dependency on jakarta.activation-api, but that did not make it in TomEE (yet).

**Comment by lukasj** [comment]
that's all related to the donation of JavaEE to Eclipse.org, I believe. If a replacement for 'javax.activation' is needed then the artifact is 'jakarta.activation' (api+impl bundle), for the naming convention, see: https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules (google can help to find JavaEE related original version of that document).
For the maven coordinates related changes, see: https://wiki.eclipse.org/New_Maven_Coordinates
